### ISSUE TITLE
Fresh pull cannot build

### ISSUE THREAD

**Issue by drunknbass** [yahoo/fluxible.io#114]
```
Error: Cannot find module './../secrets'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/drunknbass/Projects/fluxible.io/services/docs.js:11:15)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/drunknbass/Projects/fluxible.io/node_modules/babel/lib/babel/api/register/node.js:119:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/drunknbass/Projects/fluxible.io/node_modules/babel/lib/babel/api/register/node.js:132:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
10 Apr 16:36:13 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jedireza** [comment]
There is a `/secrets.example.js` file that you need to copy to `/secrets.js` with your GitHub API credentials. We should add a note about this in the README docs.

**Comment by mridgway** [comment]
https://github.com/yahoo/fluxible.io/pull/124 adds a note about this to the install directions.
